# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10SWSNwDITEUxVqyOHuTmccX7XOxTdyX0
"""

# 1. Install dependencies
!pip install requests beautifulsoup4 openai python-dotenv -q

# 2. Imports
import os
import re
import requests
from bs4 import BeautifulSoup
from openai import OpenAI
import sys
import time
import urllib.parse
from IPython.display import clear_output


os.environ["OPENAI_API_KEY"] = "sk-proj-8-1r6A"    # Add API Key here

print(" Setup complete! Ready for console demo...")


class ConsoleWebsiteChatbot:
    def __init__(self, website_url):
        self.website_url = website_url
        self.domain = urllib.parse.urlparse(website_url).netloc
        self.client = OpenAI()
        self.scraped_data = {}
        self.context = ""
        print(f"\n Initializing for: {self.domain}")

    def banner(self):
        print("\n" + "="*60)
        print(" WEBSITE CHATBOT - CONSOLE DEMO")
        print(f" Analyzing: {self.website_url}")
        print("="*60)

    def scrape_website(self):
        """Scrape website (Step 2)"""
        print("\n STEP 2: SCRAPING WEBSITE...")
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }

        try:
            response = requests.get(self.website_url, headers=headers, timeout=15)
            soup = BeautifulSoup(response.content, 'html.parser')

            self.scraped_data = {
                'title': soup.title.string.strip() if soup.title else 'No title',
                'description': self._get_meta(soup, 'description'),
                'keywords': self._get_meta(soup, 'keywords'),
                'headings': [h.get_text(strip=True) for h in soup.find_all(['h1','h2','h3']) if h.get_text(strip=True)],
                'content_preview': soup.get_text()[:2000]
            }

            print(f" SUCCESS: {self.scraped_data['title']}")
            print(f" {len(self.scraped_data['headings'])} sections found")
            return True

        except Exception as e:
            print(f" SCRAPE FAILED: {e}")
            self.scraped_data = {'error': str(e)}
            return False

    def _get_meta(self, soup, name):
        meta = soup.find('meta', attrs={'name': name})
        return meta['content'] if meta else ''

    def process_data(self):
        """Process data for ChatGPT (Step 3)"""
        print("\n STEP 3: PROCESSING DATA...")

        context = f"""WEBSITE ANALYSIS: {self.website_url}

DOMAIN: {self.domain}
TITLE: {self.scraped_data.get('title', 'N/A')}
DESCRIPTION: {self.scraped_data.get('description', 'N/A')}

MAIN SECTIONS:
{chr(10).join([f"• {h}" for h in self.scraped_data.get('headings', [])[:8]])}

You are an expert assistant for this website. Answer questions accurately using ONLY the scraped content above."""

        self.context = context
        print(" Context ready ({} chars)".format(len(context)))
        return context

    def demo_chat_loop(self):
        """Console chat demo (Step 4 & 5)"""
        print("\n STEP 4 & 5: CONSOLE CHATBOT ACTIVE!")
        print("="*60)
        print(" Ask questions about the website!")
        print(" 'INFO' = Show scraped data")
        print(" 'QUIT/EXIT/BYE' = Stop demo")
        print("="*60)

        while True:
            try:
                user_input = input("\n YOU: ").strip()

                if user_input.lower() in ['quit', 'exit', 'bye', 'q']:
                    print("\n Thanks for the demo! Goodbye!")
                    break

                if user_input.lower() in ['info', 'data', 'i']:
                    print("\n SCRAPED DATA:")
                    print(json.dumps(self.scraped_data, indent=2))
                    continue

                if not user_input:
                    print(" Please ask something about the website!")
                    continue

                print(" BOT:  Thinking...")
                response = self.get_response(user_input)
                print(f" BOT: {response}")

            except KeyboardInterrupt:
                print("\n\n Demo interrupted!")
                break

    def get_response(self, user_input):
        """ChatGPT API call"""
        messages = [
            {"role": "system", "content": self.context},
            {"role": "user", "content": user_input}
        ]

        try:
            response = self.client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=messages,
                max_tokens=800,
                temperature=0.7
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            return f" API Error: {str(e)}"


def run_demo():
    print(" WEBSITE CHATBOT DEMO STARTING...")

    # Default demo URL (change as needed)
    WEBSITE_URL = "https://botpenguin.com"

    # Initialize
    bot = ConsoleWebsiteChatbot(WEBSITE_URL)
    bot.banner()

    # Step 1-3: Setup
    if bot.scrape_website():
        bot.process_data()

        # Step 4-5: Console Demo
        bot.demo_chat_loop()
    else:
        print(" Demo failed - check URL and API key")

#  RUN THE DEMO!
run_demo()